export const LOADING = "LOADING";

export const FAILED = "FAILED";

export const THOUGHTADDEDSUCCESSFULLY = "THOUGHTADDEDSUCCESSFULLY";

export const GETALLTHOUGHTS = "GETALLTHOUGHTS";

export const DELETETHOUGHT = "DELETETHOUGHT";
